default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  primary:
    <<: *default
    database: <%= ENV['POSTGRES_DB'] %>
  queue:
    <<: *default
    database: <%= ENV['SOLID_QUEUE_DB_DEV'] %>
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: <%= ENV['POSTGRES_TEST_DB'] %>
  queue:
    <<: *default
    database: <%= ENV['SOLID_QUEUE_DB_TEST'] %>
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: <%= ENV['POSTGRES_DB_PROD'] %>
  queue:
    <<: *default
    database: <%= ENV['POSTGRES_QUEUE_DB_PROD'] %>
    migrations_paths: db/queue_migrate
