production:
  send_daily_practice_reminders:
    class: PracticeReminders::DailyRemindersJob
    schedule: every day at 9am
    queue: default
    priority: 0

development:
  send_daily_practice_reminders:
    class: PracticeReminders::DailyRemindersJob
    schedule: every day at 9am
    queue: default
    priority: 0

test:
  send_daily_practice_reminders:
    class: PracticeReminders::DailyRemindersJob
    schedule: every day at 9am
    queue: default
    priority: 0
